// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component BackgroundBlurSyntax inherits Window {
    Rectangle { background-blur: 18px; }
    Rectangle { background-blur: 0px; }
    Rectangle { background-blur: -4px; }
    Rectangle { background-blur: "18px"; }
//                                >     <<error{Cannot convert string to length}
}
