//! Stable Retrospect brand decisions.

use ui_kit_slint::{
    BorderMetrics, BrandFoundation, ControlMetrics, FocusMetrics, MotionMetrics, OverlayMetrics,
    ShadowMetrics, SkeletonMetrics, ThemeMetrics, TypographyMetrics,
};

/// Retrospect's durable typography, geometry, and interaction foundation.
pub const RETROSPECT: BrandFoundation = BrandFoundation {
    brand_id: "retrospect",
    font_display: "Inter",
    font_body: "Inter",
    font_mono: "Cascadia Mono",
    metrics: ThemeMetrics {
        borders: BorderMetrics {
            width_thin: 1.0,
            width: 1.0,
            width_normal: 2.0,
            width_strong: 3.0,
            radius_none: 0.0,
            radius_xs: 2.0,
            radius_sm: 4.0,
            radius_md: 6.0,
            radius_lg: 8.0,
            radius_xl: 12.0,
            radius_2xl: 16.0,
            radius_pill: 9999.0,
            radius_button: 8.0,
            radius_card: 12.0,
            radius_input: 8.0,
            radius_modal: 12.0,
            radius_popover: 8.0,
        },
        motion: MotionMetrics {
            duration_instant: 75,
            duration_fast: 150,
            duration_base: 200,
            duration_moderate: 300,
            duration_slow: 400,
            duration_crawl: 600,
            scale_press: 0.96,
            scale_press_subtle: 0.98,
            scale_hover: 1.025,
        },
        shadows: ShadowMetrics {
            card_blur: 8.0,
            card_offset_y: 2.0,
            card_opacity: 0.32,
            overlay_blur: 24.0,
            overlay_offset_y: 8.0,
            overlay_opacity: 0.38,
            modal_blur: 32.0,
            modal_offset_y: 12.0,
            modal_opacity: 0.44,
            glow_md_blur: 16.0,
            glow_md_opacity: 0.25,
            glow_lg_blur: 24.0,
            glow_lg_opacity: 0.35,
        },
        controls: ControlMetrics {
            button_height_xs: 28.0,
            button_height_sm: 32.0,
            button_height_md: 36.0,
            button_height_lg: 40.0,
            input_height: 36.0,
            select_height: 36.0,
            icon_size_sm: 14.0,
            icon_size_md: 16.0,
            icon_size_lg: 24.0,
        },
        focus: FocusMetrics {
            ring_width: 3.0,
            ring_offset: 2.0,
        },
        overlays: OverlayMetrics {
            scrim_subtle_opacity: 0.30,
            scrim_opacity: 0.45,
            scrim_strong_opacity: 0.60,
        },
        skeleton: SkeletonMetrics {
            base_opacity: 0.08,
            highlight_opacity: 0.14,
            shimmer_duration: 1200,
            pulse_duration: 1600,
        },
        typography: TypographyMetrics {
            size_3xs: 10.0,
            size_2xs: 11.0,
            size_xs: 12.0,
            size_sm: 13.0,
            size_md: 14.0,
            size_lg: 16.0,
            size_xl: 18.0,
            size_2xl: 28.0,
            size_display: 40.0,
            tracking_tight: -0.03,
            tracking_normal: 0.0,
            tracking_wide: 0.04,
            tracking_wider: 0.08,
            weight_regular: 400,
            weight_medium: 500,
            weight_semibold: 600,
            weight_bold: 700,
        },
    },
};
